language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.5"
install:
  - pip install .
  - pip install -rrequirements.txt
script: python -m pytest tests
notifications:
  email:
    - peter@goldsborough.me
